### PR TITLE
CClient: Fix missing transaction hash in iota_client_send_trytes API

### LINKED ISSUE #1201: CClient: transaction hash is missing in iota_client_send_trytes API.
**Describe the bug**
The transaction hash is missing in the returned object `out_transactions` when calling `iota_client_send_trytes`.

**To Reproduce**
1. Call `iota_client_send_trytes`
2. using `transaction_obj_dump` to print the returned object, the transaction hash is NULL.

**Expected behavior**
The returned transaction should contain the transaction hash.

### PR DESCRIPTION
**Pull request by jkrvivian**
Close #1201 
Enable `compute_hash` in `transaction_deserialize_from_trits` then we can get hash

# Test Plan:
1. Call `iota_client_send_trytes`
2. Use `transaction_obj_dump` to print the returned object

### CODE REVIEW

**Review by oopsmonk — CHANGES_REQUESTED** [review]
Recalculating transaction hash is too expensive since we can get it from transaction trytes.

**Comment by jkrvivian** [comment]
@oopsmonk , 
I think we can't get transaction hash from trytes directly, is there any other strategy to get hash without calculation?

**Comment by oopsmonk** [comment]
> @oopsmonk ,
> I think we can't get transaction hash from trytes directly, is there any other strategy to get hash without calculation?

yeah, you're right, I thought we could get it from `iota_client_attach_to_tangle` but it's not.

**Comment by jkrvivian** [comment]
Then the only way to get hash is to set the flag and recalculate, right?

**Comment by oopsmonk** [comment]
> Then the only way to get hash is to set the flag and recalculate, right?

yes, let's keep it simple.

**Review by oopsmonk — APPROVED** [review]

**Pull request merged**
