### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by howjmay**
The asterisk in the document doesn't align to other asterisk

### CODE REVIEW

**Comment by jserv** [comment]
It was not typo fix. Instead, it should be minor style tweak.

**Comment by howjmay** [comment]
should I remove it ?

**Comment by jserv** [comment]
@HowJMay, Read [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) carefully and use `git rebase -i` to rework the existing commit.

**Comment by howjmay** [comment]
Got it! Thank you

**Pull request closed without merging**
