### PR TITLE
utils: remove pointer to containers

### PR DESCRIPTION
**Pull request by howjmay**
Remove not necessary pointer to container.

I opened this draft to make sure I am going on the right way

### CODE REVIEW

**Comment by howjmay** [comment]
@thibault-martinez May you take a galnce is the way I did OK?

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
Sorry for the delay, we were having SumSum.
It looks good, please fix the clang-format issues, not sure why you touched C++ files.

**Comment by howjmay** [comment]
> Sorry for the delay, we were having SumSum.
> It looks good, please fix the clang-format issues, not sure why you touched C++ files.

I guess why I touch `cpp` files was formater's problem, I will fix this later.

**Comment by thibault-martinez** [comment]
@HowJMay You can probably set the PR as ready to review now

**Comment by thibault-martinez** [comment]
Looks like there are issues with the CI though

**Comment by howjmay** [comment]
> Looks like there are issues with the CI though

I am waiting for #1315. On my machine I can't build `entangled` sucessfully, because of #1315. Therefore, I haven't done a comprehensive testing yet. But thanks for you help me run the CI. Now, I am able to find out the problems ^_<

**Comment by thibault-martinez** [comment]
You can use the `--build_tests_only` option of `bazel test` to bypass this issue.

**Comment by howjmay** [comment]
That option is really helpful. 
I run the test and the only test hasn't passed is `test_exit_probability_randomizer` which would timeout. I think it is caused by some environment setting issue (setting db or something), so I push the current code and wait for the CI result anyway.

**Comment by howjmay** [comment]
I still not sure what caused my timeout problem, but, whatever, I passed test with command `bazel test --build_tests_only --remote_upload_local_results=false //ciri/consensus/...`
The timeout problem disapear with this command.

**Comment by thibault-martinez** [comment]
`test_exit_probability_randomizer` is based on random, if you're extremely unlucky it can fail :trollface:

**Review by thibault-martinez — APPROVED** [review]
Thanks!

**Comment by howjmay** [comment]
> `test_exit_probability_randomizer` is based on random, if you're extremely unlucky it can fail :trollface:

How unlucky I was .....
thanks man

**Pull request merged**
