### PR TITLE
Add option -c for conf file path

### LINKED ISSUE #1160: ciri: add -c CLI option for conf file path

### PR DESCRIPTION
**Pull request by howjmay**
use "ciri/conf.yml" as default configure file path.

Fixes #1160

### CODE REVIEW

**Review by thibault-martinez — CHANGES_REQUESTED** [review]
This issue is actually a little bit more complex than that.
Configuration variables are initialised like this: Default -> File -> CLI.
So you need to have the configuration file already.

**Comment by howjmay** [comment]
I will try to fix the problems, thanks!

**Comment by howjmay** [comment]
Could I initialized in the order Default -> CLI -> File, and cover the set the unset configures with the value in File?

**Comment by thibault-martinez** [comment]
@HowJMay You can't. Variables both in CLI and File would have the value of the File and we don't want that. I guess you'll have to do a first iteration just to get the value of `-c` from the CLI, use it to do File and then do CLI for real.

**Comment by thibault-martinez** [comment]
Sorry I didn't see that you fixed it.
Please never hesitate to click the re-request review button, it will send us a notification so that we are aware of the changes.
image

**Review by thibault-martinez — APPROVED** [review]

**Comment by thibault-martinez** [comment]
Thanks!

**Comment by howjmay** [comment]
@thibault-martinez Thank you for informing. I will use the re-request next time.><

**Pull request merged**
