### PR TITLE
License existing code under Apache-2.0

### PR DESCRIPTION
**Pull request by th0br0**
This PR finally adds an open-source license to the `entangled` repository. We have decided to release the codebase under the terms of the Apache 2.0 license.

Currently, there exist the following non-IOTA Foundation code contributors:
- [x] @jkrvivian 
- [x] @chenwei-tw 
- [x] @HowJMay 

Before we can complete this licensing change, we need approval from each of you that you are happy with licensing your existing contributions under this license. Could you please 
Could each of you please comment below this PR that you are happy with licensing your code under the terms of the Apache 2.0 license?

If you are, please comment similar to:
```
I hereby license my existing contributions to this project under the terms of the Apache 2.0 license.
```

If you are not, please comment on this PR anyway detailing why you aren't.

### CODE REVIEW

**Review by tsvisabo — APPROVED** [review]

**Comment by furuame** [comment]
I hereby license my existing contributions to this project under the terms of the Apache 2.0 license.

👍

**Comment by jkrvivian** [comment]
I hereby license my existing contributions to this project under the terms of the Apache 2.0 license.
:smile:

**Comment by howjmay** [comment]
sorry for answering last, I am serving military in the recent a few months, so I have few time using github haha
I hereby license my existing contributions to this project under the terms of the Apache 2.0 license.

**Comment by th0br0** [comment]
Thank you everyone! :)

**Pull request merged**
