### PR TITLE
Consensus init/start/stop/destroy

### LINKED ISSUE #337: Global init function for all consensus modules

### PR DESCRIPTION
**Pull request by thibault-martinez**
This PR adds a way to init, start, stop and destroy all consensus components as a whole.
Fixes #337 

# Test Plan:
Not applicable

### CODE REVIEW

**Review by tsvisabo — CHANGES_REQUESTED** [review]
Can you also check if you can use `consensus_init` in the `exit_probability_*` tests instead of `init_epv`?

**Comment by th0br0** [comment]
:thinking: instead of that `testnet` flag we should much rather hand a `network_config_t`  struct around that is setup with the various parameters we care about (req hash length, mwm, ...) but that's a separate issue. lgtm otherwise

**Comment by thibault-martinez** [comment]
Agreed, I opened https://github.com/iotaledger/entangled/issues/381 earlier for that

**Comment by thibault-martinez** [comment]
@tsvisabo I can, but I wouldn't be able to set `mt.latest_snapshot->index = 99999999999;`, or set it for every test.
Ok, nvm

**Review by tsvisabo — APPROVED** [review]

**Pull request merged**
